name: CI/CD pipeline

on:
  push:
    branches: [master, dev, test]
  workflow_dispatch:

jobs:
  # 🔹 DEV STAGE
  dev:
    name: Dev Stage
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Dev build
        run: echo "Running dev Environment"

  # 🔹 TEST STAGE
  test:
    name: Test Stage
    if: github.ref_name == 'test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Test build
        run: echo "Running test Environment"

  # 🔹 PRODUCTION DEPLOYMENT
  deploy:
    name: Deploy to Production
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload Website Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
