jobs:

  dev:
    if: github.ref_name == 'dev' || github.ref_name == 'test' || github.ref_name == 'master'
    name: Dev Stage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "Running dev Environment"

  test:
    if: github.ref_name == 'test' || github.ref_name == 'master'
    needs: dev
    name: Test Stage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "Running test Environment"

  deploy:
    if: github.ref_name == 'master'
    needs: test
    name: Deploy to GitHub Pages

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - id: deployment
        uses: actions/deploy-pages@v5
